### ISSUE TITLE
Reliable way to check if a checked translation unit/file is part of O2

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/O2CodeChecker#17]
Getting too many reports from headers outside of O2. The header filter does not seem to work as wanted. The proposition is to code a function `isFileNameMatching(regex)` ... and exit checks early if not.

**Comment by ktf** [comment]
Isn't what I do in:

```
https://github.com/AliceO2Group/O2CodeChecker/blob/master/aliceO2/MemberNamesCheck.cpp#L62
```

enough?

**Comment by sawenzel** [comment]
It isn't. This is filtering on a namespace (which might be a wrong assumption that everything we do is already in a namespace). My intention is also more to have some global service function that filters if the file being parsed is part of the correct repository. This function can than be reused in all the checks.

**Comment by sawenzel** [comment]
Seems like we could use
a) clang matchers for this
```
Matcher<Decl> | isExpansionInFileMatching | std::string RegExp
Matcher<Decl> | isExpansionInMainFile
```
b) query the filename from the source location and the source manager with `SourceManager::getFilename(sourceLocation)`

**Comment by ktf** [comment]
Yes, that sounds reasonable. We should make sure it's done at the right point in the matcher, to avoid one regex per node it attempts to match.

**Comment by sawenzel** [comment]
Solved via configuration passed in a .clang-tidy file:

for example:
```
CheckOptions:
+  - key: CheckPathRegex
+    value: '.*/O2/.*'
```
